### ISSUE TITLE
[bug] in-appropriate version and usage

### ISSUE THREAD

**Issue by shiv-sk** [reactjsdevelopment/appwrite-demo#6]
The project is using React Router v6, where useHistory has been removed. However, the project still includes code that uses useHistory, causing a syntax error when users open the project. 

![Screenshot (68)](https://github.com/user-attachments/assets/61b970dc-f9ae-4753-84ae-b4a48deef9e1)

**Comment by sunny7899** [comment]
go ahead @shiv-sk
